In [1]:
import pandas as pd
import numpy as np

In [ ]:
file_path = '../Jeux de données-20260109/Flights_20191201_20191231.csv/Flights_20191201_20191231.csv'

# Chargement avec paramètres spécifiques
df_Flights_20191201_20191231 = pd.read_csv(
                                file_path,
                                sep=',',              # Définit le séparateur (souvent ; en France)
                                encoding='utf-8',     # Encodage (essayer 'latin1' ou 'cp1252' si erreur)
                                index_col=0,          # Utilise la 1ère colonne comme index (optionnel)
                                na_values=['n/a', '?'] # Convertit ces valeurs spécifiques en NaN (vide)
                            )

In [ ]:
def select_air_france(df): 
    df_select = df[df['AC Operator'] == 'AFR']

    print("Nombre de vols air france: ", len(df_select))
    return df_select

def select_europe(df): 
    codes_europe = ['L', 'E', 'B']

    # 3. On crée un filtre : Le 1er caractère de ADEP *ET* de ADES doit être dans la liste
    # .str[0] permet de prendre juste la première lettre de la colonne
    filtre_europe = (
        df['ADEP'].str[0].isin(codes_europe) & 
        df['ADES'].str[0].isin(codes_europe)
    )

    # 4. On applique le filtre
    vols_europe = df[filtre_europe]

    print(f"Nombre de vols trouvés : {len(vols_europe)}")
    print(vols_europe[['ADEP', 'ADES']].head())

    return vols_europe

# def top_flights(df, n_top = 100): 
#     classement_liaisons = df.groupby(['ADEP', 'ADES']).size()
#     classement_liaisons = classement_liaisons.sort_values(ascending=False)
#     classement_liaisons = classement_liaisons.reset_index(name='Nombre_de_vols')
#     # Affichage du TOP 10
#     print("Top 10 des liaisons Air France en Europe :")
#     print(classement_liaisons.head(n_top))

#     return classement_liaisons.head(n_top)

def top_flights(df, n_top=100):
    df_temp = df.copy()

    routes_triees = np.sort(df_temp[['ADEP', 'ADES']].values, axis=1)

    df_temp['Aeroport_1'] = routes_triees[:, 0]
    df_temp['Aeroport_2'] = routes_triees[:, 1]

    classement_liaisons = df_temp.groupby(['Aeroport_1', 'Aeroport_2']).size()

    classement_liaisons = classement_liaisons.sort_values(ascending=False)
    classement_liaisons = classement_liaisons.reset_index(name='Nombre_de_vols')


    print(f"Top {n_top} des liaisons (Sens confondus) :")
    print(classement_liaisons.head(n_top))

    return classement_liaisons.head(n_top)

# def selec_top_flights(df, top_flight): 
#     clés_top_10 = top_flight[['Aeroport_1', 'Aeroport_2']] + top_flight[['Aeroport_2', 'Aeroport_1']]

#     masque_filtre = (
#         df.set_index(['ADEP', 'ADES']).index.isin(clés_top_10.set_index(['ADEP', 'ADES']).index)
#     )

#     # 3. On applique ce masque au DataFrame original
#     vols_du_top = df[masque_filtre]

#     # Vérification
#     print("Nombre de vols retenus : ", len(vols_du_top))

#     return vols_du_top

def selec_top_flights(df, top_flight):
    # 1. Préparation de la liste complète des couples autorisés (A->B ET B->A)
    
    # On prend le sens "Aller" (tel quel dans le top) et on renomme pour matcher df
    sens_aller = top_flight[['Aeroport_1', 'Aeroport_2']].rename(
        columns={'Aeroport_1': 'ADEP', 'Aeroport_2': 'ADES'}
    )
    
    # On prend le sens "Retour" (on inverse les colonnes) et on renomme pour matcher df
    sens_retour = top_flight[['Aeroport_2', 'Aeroport_1']].rename(
        columns={'Aeroport_2': 'ADEP', 'Aeroport_1': 'ADES'}
    )
    
    # On concatène les deux pour avoir une liste exhaustive de toutes les paires valides
    toutes_les_cles = pd.concat([sens_aller, sens_retour])

    # 2. Création du masque
    # On vérifie si le couple (ADEP, ADES) du vol existe dans notre liste exhaustive
    masque_filtre = (
        df.set_index(['ADEP', 'ADES']).index.isin(toutes_les_cles.set_index(['ADEP', 'ADES']).index)
    )

    # 3. On applique ce masque au DataFrame original
    vols_du_top = df[masque_filtre]

    # Vérification
    print(f"Nombre de vols retenus : {len(vols_du_top)} (sur {len(df)})")

    return vols_du_top

In [ ]:
print("Nombre de vols décembre en Europe :", len(df_Flights_20191201_20191231))
print("\n")
vols_af = select_air_france(df_Flights_20191201_20191231)
print("\n")
vols_af_europe = select_europe(vols_af)
print("\n")
top_lines = top_flights(vols_af_europe, 20)
print("\n")
top_vols_af_europe = selec_top_flights(vols_af_europe, top_lines)

Nombre de vols décembre en Europe : 747570


Nombre de vols air france:  30421


Nombre de vols trouvés : 24244
           ADEP  ADES
ECTRL ID
236565987  LTFM  LFPG
236566467  LROP  LFPG
236566523  LGAV  LFPG
236566830  LFML  LFPG
236566832  LHBP  LFPG


Top 20 des liaisons (Sens confondus) :
   Aeroport_1 Aeroport_2  Nombre_de_vols
0        LFBO       LFPO             940
1        LFMN       LFPO             750
2        LFML       LFPO             603
3        LFPG       LSGG             522
4        LFMT       LFPO             490
5        LFBD       LFPO             475
6        LFMN       LFPG             434
7        LFBO       LFPG             419
8        LEBL       LFPG             414
9        LFML       LFPG             381
10       EGLL       LFPG             366
11       LEMD       LFPG             364
12       EHAM       LFPG             360
13       LFBD       LFPG             356
14       LFPG       LIRF             353
15       EDDT       LFPG             346
16       EDDM       LFPG             324
17       LFLL       LFPG             309
18       EDDF       LFPG             297
19       LFPO       LFTH             293


Nombre de vols retenus : 8796 (sur 24244)

In [ ]:
top_vols_af_europe['AC Type'].unique()

array(['A319', 'A318', 'A320', 'A321', 'E190', 'CRJ7', 'CRJX', 'E170',
       'E145', 'B789'], dtype=object)

In [ ]:
# Dictionnaire de correspondance (OACI -> Ville)
dico_villes = {
    'LFBO': 'Toulouse', 'LFPO': 'Paris-Orly', 'LFMN': 'Nice', 
    'LFML': 'Marseille', 'LFPG': 'Paris-CDG', 'LSGG': 'Genève', 
    'LFMT': 'Montpellier', 'LFBD': 'Bordeaux', 'LEBL': 'Barcelone', 
    'EGLL': 'Londres-Heathrow', 'LEMD': 'Madrid', 'EHAM': 'Amsterdam', 
    'LIRF': 'Rome', 'EDDT': 'Berlin', 'EDDM': 'Munich', 
    'LFLL': 'Lyon', 'EDDF': 'Francfort', 'LFTH': 'Toulon'
}

# Supposons que votre dataframe de résultat s'appelle 'top_20'
# On ajoute les colonnes Ville
top_lines['Ville_1'] = top_lines['Aeroport_1'].map(dico_villes)
top_lines['Ville_2'] = top_lines['Aeroport_2'].map(dico_villes)

# On affiche pour vérifier
print(top_lines[['Ville_1', 'Ville_2', 'Nombre_de_vols']])

             Ville_1     Ville_2  Nombre_de_vols
0           Toulouse  Paris-Orly             940
1               Nice  Paris-Orly             750
2          Marseille  Paris-Orly             603
3          Paris-CDG      Genève             522
4        Montpellier  Paris-Orly             490
5           Bordeaux  Paris-Orly             475
6               Nice   Paris-CDG             434
7           Toulouse   Paris-CDG             419
8          Barcelone   Paris-CDG             414
9          Marseille   Paris-CDG             381
10  Londres-Heathrow   Paris-CDG             366
11            Madrid   Paris-CDG             364
12         Amsterdam   Paris-CDG             360
13          Bordeaux   Paris-CDG             356
14         Paris-CDG        Rome             353
15            Berlin   Paris-CDG             346
16            Munich   Paris-CDG             324
17              Lyon   Paris-CDG             309
18         Francfort   Paris-CDG             297
19        Paris-Orly      Toulon             293

# Analyse des résultats

## Lignes existantes

In [19]:
existing_plane_lines = pd.read_csv('optimisation_vols_existants.csv', sep=';', encoding='utf-8')
existing_plane_lines

,Départ,Arrivée,CO2_Avion_Direct,CO2_Optimisé,Gain_CO2_kg,Gain_CO2_%,Allongement_min,Trajet_Retenu
0,Istanbul,Izmir,2618.04,2618.04,0.0,0.0,0.0,Istanbul->Izmir (avion)
1,Izmir,Istanbul,2682.14,2682.14,0.0,0.0,0.0,Izmir->Istanbul (avion)
2,Ankara,Istanbul,2571.55,2571.55,0.0,0.0,0.0,Ankara->Istanbul (avion)
3,Istanbul,Ankara,2471.77,2471.77,0.0,0.0,0.0,Istanbul->Ankara (avion)
4,Madrid,Barcelone,3102.97,2.96,3100.0,99.9,-1.0,Madrid->Barcelone (train)
...,...,...,...,...,...,...,...,...
2949,Rennes,Amsterdam,2110.99,2110.99,0.0,0.0,0.0,Rennes->Amsterdam (avion)
2950,Katowice,Eindhoven,3893.54,3893.54,0.0,0.0,0.0,Katowice->Eindhoven (avion)
2951,Alesund,Trondheim,1932.73,1932.73,0.0,0.0,0.0,Alesund->Trondheim (avion)
2952,Kirkwall,Sumburgh,247.86,247.86,0.0,0.0,0.0,Kirkwall->Sumburgh (avion)
2953,Oslo,Sandane,495.77,495.77,0.0,0.0,0.0,Oslo->Sandane (avion)

In [21]:
mask = existing_plane_lines['Gain_CO2_kg'] > 0
gain_co2_epl=existing_plane_lines[mask]
gain_co2_epl

,Départ,Arrivée,CO2_Avion_Direct,CO2_Optimisé,Gain_CO2_kg,Gain_CO2_%,Allongement_min,Trajet_Retenu
4,Madrid,Barcelone,3102.97,2.96,3100.00,99.90,-1.0,Madrid->Barcelone (train)
5,Barcelone,Madrid,3019.86,2.96,3016.90,99.90,-6.0,Barcelone->Madrid (train)
18,Dublin,Londres,2568.56,2295.08,273.49,10.65,113.1,Dublin->Birmingham (avion) | Birmingham->Londr...
26,Rome,Milan,1966.90,7.65,1959.25,99.61,26.2,Rome->Milan (train)
27,Milan,Rome,2030.30,7.65,2022.65,99.62,27.7,Milan->Rome (train)
...,...,...,...,...,...,...,...,...
2929,Istanbul,Leipzig,6721.81,6414.83,306.98,4.57,152.2,Istanbul->Vienne (avion) | Vienne->Leipzig (av...
2930,Nice,Istanbul,8593.13,7245.40,1347.73,15.68,165.9,Nice->Rome (avion) | Rome->Istanbul (avion)
2931,Toulouse,Istanbul,8628.74,8542.30,86.43,1.00,148.5,Toulouse->Marseille (avion) | Marseille->Istan...
2943,Dublin,Lyon,4608.32,3587.79,1020.53,22.15,141.2,Dublin->Paris (avion) | Paris->Lyon (train)
2947,Séville,Bruxelles,6598.19,5227.53,1370.66,20.77,155.1,Séville->Paris (avion) | Paris->Lille (train) ...

In [26]:
gain_co2_epl.loc[2929]['Trajet_Retenu']

'Istanbul->Vienne (avion) | Vienne->Leipzig (avion)'

In [23]:
print(existing_plane_lines["Allongement_min"].mean())
print(gain_co2_epl["Allongement_min"].mean())

28.95318212593094
124.71140215716488

## Villes avec aéroports et gares

In [17]:
airports_gare = pd.read_csv('bilan_airport_train.csv', sep=';', encoding='utf-8')
airports_gare

,Départ,Arrivée,CO2_Avion_Direct,CO2_Optimisé,Gain_CO2_%,Allongement_min,Trajet_Retenu
0,Paris,Nantes,2389.90,1.01,99.96,-33.5,Paris->Nantes (train)
1,Nantes,Paris,2408.51,1.01,99.96,-31.1,Nantes->Paris (train)
2,Rennes,Paris,1558.03,0.74,99.95,-55.4,Rennes->Paris (train)
3,Paris,Rennes,1475.31,0.74,99.95,-60.1,Paris->Rennes (train)
4,Bordeaux,Paris,2229.56,1.09,99.95,-29.7,Bordeaux->Paris (train)
...,...,...,...,...,...,...,...
883,Prague,Genève,3303.89,3303.89,0.00,0.0,Prague->Genève (avion)
884,Genève,Prague,3376.20,3376.20,0.00,0.0,Genève->Prague (avion)
885,Varsovie,Venise,3028.41,3028.41,0.00,0.0,Varsovie->Venise (avion)
886,La Corogne,Londres,4252.07,4252.07,0.00,0.0,La Corogne->Londres (avion)
887,Francfort,Berlin,2812.77,2812.77,0.00,0.0,Francfort->Berlin (avion)

In [6]:
mask = airports_gare['Trajet_Retenu'].str.contains('avion') & airports_gare['Trajet_Retenu'].str.contains('train')
resultat = airports_gare[mask]
resultat

,Départ,Arrivée,CO2_Avion_Direct,CO2_Optimisé,Gain_CO2_%,Allongement_min,Trajet_Retenu
106,Madrid,Paris,4017.68,1888.14,53.00,124.8,Madrid->Bordeaux (avion) | Bordeaux->Paris (tr...
107,Paris,Madrid,4021.05,1893.45,52.91,122.6,Paris->Bordeaux (train) | Bordeaux->Madrid (av...
108,Berlin,Amsterdam,2901.19,1498.53,48.35,122.8,Berlin->Hanovre (train) | Hanovre->Amsterdam (...
109,Newcastle,Paris,2714.77,1404.68,48.26,119.2,Newcastle->Bruxelles (avion) | Bruxelles->Pari...
110,Paris,Bologne,3423.25,1777.66,48.07,135.4,Paris->Lyon (train) | Lyon->Bologne (avion)
...,...,...,...,...,...,...,...
338,Paris,Florence,3471.79,3424.82,1.35,86.2,Paris->Bologne (avion) | Bologne->Florence (tr...
341,Florence,Paris,3381.76,3358.65,0.68,83.8,Florence->Bologne (train) | Bologne->Paris (av...
342,Munich,Nantes,3284.95,3265.52,0.59,136.7,Munich->Paris (avion) | Paris->Nantes (train)
343,Bruxelles,Rome,4676.35,4648.98,0.59,124.7,Bruxelles->Paris (train) | Paris->Rome (avion)
345,Paris,Venise,3416.03,3413.58,0.07,124.0,Paris->Bruxelles (train) | Bruxelles->Venise (...

In [20]:
allongement_max = resultat.sort_values(by='Allongement_min', ascending=True)
allongement_max.head()

,Départ,Arrivée,CO2_Avion_Direct,CO2_Optimisé,Gain_CO2_%,Allongement_min,Trajet_Retenu
314,Amsterdam,Florence,3651.69,3493.60,4.33,74.1,Amsterdam->Bologne (avion) | Bologne->Florence...
229,Munich,Florence,2364.82,2044.18,13.56,74.9,Munich->Bologne (avion) | Bologne->Florence (t...
258,Barcelone,Bologne,3728.50,3332.87,10.61,74.9,Barcelone->Florence (avion) | Florence->Bologn...
261,Bologne,Barcelone,3676.92,3301.21,10.22,75.8,Bologne->Florence (train) | Florence->Barcelon...
249,Florence,Munich,2342.80,2080.99,11.17,78.8,Florence->Bologne (train) | Bologne->Munich (a...

In [14]:
resultat['Allongement_min'].dtype

dtype('float64')